package net.cmr.jurassicrevived.datagen;

import net.cmr.jurassicrevived.JRMod;
import net.cmr.jurassicrevived.block.ModBlocks;
import net.cmr.jurassicrevived.item.ModItems;
import net.cmr.jurassicrevived.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModItemTagProvider extends ItemTagsProvider {

    public ModItemTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, CompletableFuture<TagLookup<Block>> blockTags, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, blockTags, JRMod.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        this.tag(ModTags.Items.TISSUES)
                .add(ModItems.APATOSAURUS_TISSUE.get())
                .add(ModItems.ALBERTOSAURUS_TISSUE.get())
                .add(ModItems.BRACHIOSAURUS_TISSUE.get())
                .add(ModItems.CERATOSAURUS_TISSUE.get())
                .add(ModItems.COMPSOGNATHUS_TISSUE.get())
                .add(ModItems.DILOPHOSAURUS_TISSUE.get())
                .add(ModItems.DIPLODOCUS_TISSUE.get())
                .add(ModItems.GALLIMIMUS_TISSUE.get())
                .add(ModItems.INDOMINUS_REX_TISSUE.get())
                .add(ModItems.OURANOSAURUS_TISSUE.get())
                .add(ModItems.PARASAUROLOPHUS_TISSUE.get())
                .add(ModItems.SPINOSAURUS_TISSUE.get())
                .add(ModItems.TRICERATOPS_TISSUE.get())
                .add(ModItems.TYRANNOSAURUS_REX_TISSUE.get())
                .add(ModItems.VELOCIRAPTOR_TISSUE.get())
                .add(ModItems.BARYONYX_TISSUE.get())
                .add(ModItems.CARNOTAURUS_TISSUE.get())
                .add(ModItems.CONCAVENATOR_TISSUE.get())
                .add(ModItems.DEINONYCHUS_TISSUE.get())
                .add(ModItems.EDMONTOSAURUS_TISSUE.get())
                .add(ModItems.GIGANOTOSAURUS_TISSUE.get())
                .add(ModItems.GUANLONG_TISSUE.get())
                .add(ModItems.HERRERASAURUS_TISSUE.get())
                .add(ModItems.MAJUNGASAURUS_TISSUE.get())
                .add(ModItems.PROCOMPSOGNATHUS_TISSUE.get())
                .add(ModItems.PROTOCERATOPS_TISSUE.get())
                .add(ModItems.RUGOPS_TISSUE.get())
                .add(ModItems.SHANTUNGOSAURUS_TISSUE.get())
                .add(ModItems.STEGOSAURUS_TISSUE.get())
                .add(ModItems.STYRACOSAURUS_TISSUE.get())
                .add(ModItems.THERIZINOSAURUS_TISSUE.get())
                .add(ModItems.DISTORTUS_REX_TISSUE.get());
        this.tag(ModTags.Items.DNA)
                .add(ModItems.APATOSAURUS_DNA.get())
                .add(ModItems.ALBERTOSAURUS_DNA.get())
                .add(ModItems.BRACHIOSAURUS_DNA.get())
                .add(ModItems.CERATOSAURUS_DNA.get())
                .add(ModItems.COMPSOGNATHUS_DNA.get())
                .add(ModItems.DILOPHOSAURUS_DNA.get())
                .add(ModItems.DIPLODOCUS_DNA.get())
                .add(ModItems.GALLIMIMUS_DNA.get())
                .add(ModItems.INDOMINUS_REX_DNA.get())
                .add(ModItems.OURANOSAURUS_DNA.get())
                .add(ModItems.PARASAUROLOPHUS_DNA.get())
                .add(ModItems.SPINOSAURUS_DNA.get())
                .add(ModItems.TRICERATOPS_DNA.get())
                .add(ModItems.TYRANNOSAURUS_REX_DNA.get())
                .add(ModItems.VELOCIRAPTOR_DNA.get())
                .add(ModItems.BARYONYX_DNA.get())
                .add(ModItems.CARNOTAURUS_DNA.get())
                .add(ModItems.CONCAVENATOR_DNA.get())
                .add(ModItems.DEINONYCHUS_DNA.get())
                .add(ModItems.EDMONTOSAURUS_DNA.get())
                .add(ModItems.GIGANOTOSAURUS_DNA.get())
                .add(ModItems.GUANLONG_DNA.get())
                .add(ModItems.HERRERASAURUS_DNA.get())
                .add(ModItems.MAJUNGASAURUS_DNA.get())
                .add(ModItems.PROCOMPSOGNATHUS_DNA.get())
                .add(ModItems.PROTOCERATOPS_DNA.get())
                .add(ModItems.RUGOPS_DNA.get())
                .add(ModItems.SHANTUNGOSAURUS_DNA.get())
                .add(ModItems.STEGOSAURUS_DNA.get())
                .add(ModItems.STYRACOSAURUS_DNA.get())
                .add(ModItems.THERIZINOSAURUS_DNA.get())
                .add(ModItems.DISTORTUS_REX_DNA.get());
        this.tag(ModTags.Items.SYRINGES)
                .add(ModItems.APATOSAURUS_SYRINGE.get())
                .add(ModItems.ALBERTOSAURUS_SYRINGE.get())
                .add(ModItems.BRACHIOSAURUS_SYRINGE.get())
                .add(ModItems.CERATOSAURUS_SYRINGE.get())
                .add(ModItems.COMPSOGNATHUS_SYRINGE.get())
                .add(ModItems.DILOPHOSAURUS_SYRINGE.get())
                .add(ModItems.DIPLODOCUS_SYRINGE.get())
                .add(ModItems.GALLIMIMUS_SYRINGE.get())
                .add(ModItems.INDOMINUS_REX_SYRINGE.get())
                .add(ModItems.OURANOSAURUS_SYRINGE.get())
                .add(ModItems.PARASAUROLOPHUS_SYRINGE.get())
                .add(ModItems.SPINOSAURUS_SYRINGE.get())
                .add(ModItems.TRICERATOPS_SYRINGE.get())
                .add(ModItems.TYRANNOSAURUS_REX_SYRINGE.get())
                .add(ModItems.VELOCIRAPTOR_SYRINGE.get())
                .add(ModItems.BARYONYX_SYRINGE.get())
                .add(ModItems.CARNOTAURUS_SYRINGE.get())
                .add(ModItems.CONCAVENATOR_SYRINGE.get())
                .add(ModItems.DEINONYCHUS_SYRINGE.get())
                .add(ModItems.EDMONTOSAURUS_SYRINGE.get())
                .add(ModItems.GIGANOTOSAURUS_SYRINGE.get())
                .add(ModItems.GUANLONG_SYRINGE.get())
                .add(ModItems.HERRERASAURUS_SYRINGE.get())
                .add(ModItems.MAJUNGASAURUS_SYRINGE.get())
                .add(ModItems.PROCOMPSOGNATHUS_SYRINGE.get())
                .add(ModItems.PROTOCERATOPS_SYRINGE.get())
                .add(ModItems.RUGOPS_SYRINGE.get())
                .add(ModItems.SHANTUNGOSAURUS_SYRINGE.get())
                .add(ModItems.STEGOSAURUS_SYRINGE.get())
                .add(ModItems.STYRACOSAURUS_SYRINGE.get())
                .add(ModItems.THERIZINOSAURUS_SYRINGE.get())
                .add(ModItems.DISTORTUS_REX_SYRINGE.get());
        this.tag(ModTags.Items.EGGS)
                .add(Item.byBlock(ModBlocks.APATOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.ALBERTOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.BRACHIOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.CERATOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.COMPSOGNATHUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.DILOPHOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.DIPLODOCUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.GALLIMIMUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.INDOMINUS_REX_EGG.get()))
                .add(Item.byBlock(ModBlocks.OURANOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.PARASAUROLOPHUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.SPINOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.TRICERATOPS_EGG.get()))
                .add(Item.byBlock(ModBlocks.TYRANNOSAURUS_REX_EGG.get()))
                .add(Item.byBlock(ModBlocks.VELOCIRAPTOR_EGG.get()))
                .add(Item.byBlock(ModBlocks.BARYONYX_EGG.get()))
                .add(Item.byBlock(ModBlocks.CARNOTAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.CONCAVENATOR_EGG.get()))
                .add(Item.byBlock(ModBlocks.DEINONYCHUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.EDMONTOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.GIGANOTOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.GUANLONG_EGG.get()))
                .add(Item.byBlock(ModBlocks.HERRERASAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.MAJUNGASAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.PROCOMPSOGNATHUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.PROTOCERATOPS_EGG.get()))
                .add(Item.byBlock(ModBlocks.RUGOPS_EGG.get()))
                .add(Item.byBlock(ModBlocks.SHANTUNGOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.STEGOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.STYRACOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.THERIZINOSAURUS_EGG.get()))
                .add(Item.byBlock(ModBlocks.DISTORTUS_REX_EGG.get()));
        this.tag(ModTags.Items.FOSSILS)
                .add(ModItems.APATOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.ALBERTOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.BRACHIOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.CERATOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.COMPSOGNATHUS_SKULL_FOSSIL.get())
                .add(ModItems.DILOPHOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.DIPLODOCUS_SKULL_FOSSIL.get())
                .add(ModItems.GALLIMIMUS_SKULL_FOSSIL.get())
                .add(ModItems.PARASAUROLOPHUS_SKULL_FOSSIL.get())
                .add(ModItems.OURANOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.SPINOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.TRICERATOPS_SKULL_FOSSIL.get())
                .add(ModItems.TYRANNOSAURUS_REX_SKULL_FOSSIL.get())
                .add(ModItems.VELOCIRAPTOR_SKULL_FOSSIL.get())
                .add(ModItems.BARYONYX_SKULL_FOSSIL.get())
                .add(ModItems.CARNOTAURUS_SKULL_FOSSIL.get())
                .add(ModItems.CONCAVENATOR_SKULL_FOSSIL.get())
                .add(ModItems.DEINONYCHUS_SKULL_FOSSIL.get())
                .add(ModItems.EDMONTOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.GIGANOTOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.GUANLONG_SKULL_FOSSIL.get())
                .add(ModItems.HERRERASAURUS_SKULL_FOSSIL.get())
                .add(ModItems.MAJUNGASAURUS_SKULL_FOSSIL.get())
                .add(ModItems.PROCOMPSOGNATHUS_SKULL_FOSSIL.get())
                .add(ModItems.PROTOCERATOPS_SKULL_FOSSIL.get())
                .add(ModItems.RUGOPS_SKULL_FOSSIL.get())
                .add(ModItems.SHANTUNGOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.STEGOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.STYRACOSAURUS_SKULL_FOSSIL.get())
                .add(ModItems.THERIZINOSAURUS_SKULL_FOSSIL.get());
        this.tag(ModTags.Items.SKULLS)
                .add(ModItems.FRESH_APATOSAURUS_SKULL.get())
                .add(ModItems.FRESH_ALBERTOSAURUS_SKULL.get())
                .add(ModItems.FRESH_BRACHIOSAURUS_SKULL.get())
                .add(ModItems.FRESH_CERATOSAURUS_SKULL.get())
                .add(ModItems.FRESH_COMPSOGNATHUS_SKULL.get())
                .add(ModItems.FRESH_DILOPHOSAURUS_SKULL.get())
                .add(ModItems.FRESH_DIPLODOCUS_SKULL.get())
                .add(ModItems.FRESH_GALLIMIMUS_SKULL.get())
                .add(ModItems.FRESH_INDOMINUS_REX_SKULL.get())
                .add(ModItems.FRESH_PARASAUROLOPHUS_SKULL.get())
                .add(ModItems.FRESH_OURANOSAURUS_SKULL.get())
                .add(ModItems.FRESH_SPINOSAURUS_SKULL.get())
                .add(ModItems.FRESH_TRICERATOPS_SKULL.get())
                .add(ModItems.FRESH_TYRANNOSAURUS_REX_SKULL.get())
                .add(ModItems.FRESH_VELOCIRAPTOR_SKULL.get())
                .add(ModItems.FRESH_BARYONYX_SKULL.get())
                .add(ModItems.FRESH_CARNOTAURUS_SKULL.get())
                .add(ModItems.FRESH_CONCAVENATOR_SKULL.get())
                .add(ModItems.FRESH_DEINONYCHUS_SKULL.get())
                .add(ModItems.FRESH_EDMONTOSAURUS_SKULL.get())
                .add(ModItems.FRESH_GIGANOTOSAURUS_SKULL.get())
                .add(ModItems.FRESH_GUANLONG_SKULL.get())
                .add(ModItems.FRESH_HERRERASAURUS_SKULL.get())
                .add(ModItems.FRESH_MAJUNGASAURUS_SKULL.get())
                .add(ModItems.FRESH_PROCOMPSOGNATHUS_SKULL.get())
                .add(ModItems.FRESH_PROTOCERATOPS_SKULL.get())
                .add(ModItems.FRESH_RUGOPS_SKULL.get())
                .add(ModItems.FRESH_SHANTUNGOSAURUS_SKULL.get())
                .add(ModItems.FRESH_STEGOSAURUS_SKULL.get())
                .add(ModItems.FRESH_STYRACOSAURUS_SKULL.get())
                .add(ModItems.FRESH_THERIZINOSAURUS_SKULL.get())
                .add(ModItems.FRESH_DISTORTUS_REX_SKULL.get());
    }
}
